car_list:
  - Maruti Alto
  - Hyundai Grand
  - Hyundai i20
  - Ford Ecosport
  - Maruti Wagon R
  - Hyundai i10
  - Hyundai Venue
  - Maruti Swift
  - Hyundai Verna
  - Renault Duster
  - Mini Cooper
  - Maruti Ciaz
  - Mercedes-Benz C-Class
  - Toyota Innova
  - Maruti Baleno
  - Maruti Swift Dzire
  - Volkswagen Vento
  - Hyundai Creta
  - Honda City
  - Mahindra Bolero
  - Toyota Fortuner
  - Renault KWID
  - Honda Amaze
  - Hyundai Santro
  - Mahindra XUV500
  - Mahindra KUV100
  - Maruti Ignis
  - Datsun RediGO
  - Mahindra Scorpio
  - Mahindra Marazzo
  - Ford Aspire
  - Ford Figo
  - Maruti Vitara
  - Tata Tiago
  - Volkswagen Polo
  - Kia Seltos
  - Maruti Celerio
  - Datsun GO
  - BMW 5
  - Honda CR-V
  - Ford Endeavour
  - Mahindra KUV
  - Honda Jazz
  - BMW 3
  - Audi A4
  - Tata Tigor
  - Maruti Ertiga
  - Tata Safari
  - Mahindra Thar
  - Tata Hexa
  - Land Rover Rover
  - Maruti Eeco
  - Audi A6
  - Mercedes-Benz E-Class
  - Audi Q7
  - BMW Z4
  - BMW 6
  - Jaguar XF
  - BMW X5
  - MG Hector
  - Honda Civic
  - Isuzu D-Max
  - Porsche Cayenne
  - BMW X1
  - Skoda Rapid
  - Ford Freestyle
  - Skoda Superb
  - Tata Nexon
  - Mahindra XUV300
  - Maruti Dzire VXI
  - Volvo S90
  - Honda WR-V
  - Maruti XL6
  - Renault Triber
  - Lexus ES
  - Jeep Wrangler
  - Toyota Camry
  - Hyundai Elantra
  - Toyota Yaris
  - Mercedes-Benz GL-Class
  - BMW 7
  - Maruti S-Presso
  - Maruti Dzire LXI
  - Hyundai Aura
  - Volvo XC
  - Maserati Ghibli
  - Bentley Continental
  - Honda CR
  - Nissan Kicks
  - Mercedes-Benz S-Class
  - Hyundai Tucson
  - Tata Harrier
  - BMW X3
  - Skoda Octavia
  - Jeep Compass
  - Mercedes-Benz CLS
  - Datsun redi-GO
  - Toyota Glanza
  - Porsche Macan
  - BMW X4
  - Maruti Dzire ZXI
  - Volvo XC90
  - Jaguar F-PACE
  - Audi A8
  - ISUZU MUX
  - Ferrari GTC4Lusso
  - Mercedes-Benz GLS
  - Nissan X-Trail
  - Jaguar XE
  - Volvo XC60
  - Porsche Panamera
  - Mahindra Alturas
  - Tata Altroz
  - Lexus NX
  - Kia Carnival
  - Mercedes-AMG C
  - Lexus RX
  - Rolls-Royce Ghost
  - Maserati Quattroporte
  - Isuzu MUX
  - Force Gurkha